


--1. Muestra el nombre de las empresas productoras de Huelva o Málaga ordenadas por el
--nombre en orden alfabético inverso.
SELECT EMPRESAPRODUCTORA.NOMBRE_EMPRESA
FROM EMPRESAPRODUCTORA
WHERE UPPER(EMPRESAPRODUCTORA.CIUDAD_EMPRESA) LIKE 'HUELVA' 
OR UPPER(EMPRESAPRODUCTORA.NOMBRE_EMPRESA) LIKE 'MÁLAGA'
OR UPPER(EMPRESAPRODUCTORA.NOMBRE_EMPRESA) LIKE 'MALAGA'
ORDER BY EMPRESAPRODUCTORA.NOMBRE_EMPRESA DESC; 

--2. Mostrar los nombres de los destinos cuya ciudad contenga una b mayúscula o minúscula.
SELECT DESTINO.NOMBRE_DESTINO
FROM DESTINO
WHERE UPPER(DESTINO.NOMBRE_DESTINO) LIKE '%B%';

--3. Obtener el código de los residuos con una cantidad superior a 4 del constituyente 116.
SELECT RESIDUO_CONSTITUYENTE.COD_RESIDUO
FROM RESIDUO_CONSTITUYENTE
WHERE RESIDUO_CONSTITUYENTE.CANTIDAD > 4 
AND RESIDUO_CONSTITUYENTE.COD_CONSTITUYENTE = 116;

--4. Muestra el tipo de transporte, los kilómetros y el coste de los traslados realizados en
--diciembre de 1994.
SELECT TRASLADO.TIPO_TRANSPORTE, TRASLADO.KMS, TRASLADO.COSTE
FROM TRASLADO
WHERE EXTRACT(YEAR FROM TRASLADO.FECHA_ENVIO) = 1994
AND EXTRACT(MONTH FROM TRASLADO.FECHA_ENVIO) = 12;

--5. Mostrar el código del residuo y el número de constituyentes de cada residuo.
SELECT RESIDUO_CONSTITUYENTE.COD_RESIDUO, COUNT(RESIDUO_CONSTITUYENTE.COD_CONSTITUYENTE)num_contr
FROM RESIDUO_CONSTITUYENTE
GROUP BY RESIDUO_CONSTITUYENTE.COD_RESIDUO;

--6. Mostrar la cantidad media de residuo vertida por las empresas durante el año 1994.
SELECT NVL(AVG(NVL(RESIDUO_EMPRESA.CANTIDAD,0)),0) cantidad_media
FROM RESIDUO_EMPRESA
WHERE EXTRACT(YEAR FROM RESIDUO_EMPRESA.FECHA) = 1994;

--7. Mostrar el mayor número de kilómetros de un traslado realizado el mes de marzo.
SELECT MAX(TRASLADO.KMS) mayor_num_km
FROM TRASLADO
WHERE EXTRACT(MONTH FROM TRASLADO.FECHA_ENVIO) = 3;

--8. Mostrar el número de constituyentes distintos que genera cada empresa, mostrando también
--el nif de la empresa, para aquellas empresas que generen más de 4 constituyentes.
-- REGULAR
SELECT COUNT(DISTINCT RESIDUO_CONSTITUYENTE.COD_CONSTITUYENTE)
FROM RESIDUO_EMPRESA, RESIDUO, RESIDUO_CONSTITUYENTE
WHERE RESIDUO_EMPRESA.COD_RESIDUO = RESIDUO.COD_RESIDUO
AND RESIDUO.COD_RESIDUO = RESIDUO_CONSTITUYENTE.COD_RESIDUO
ORDER BY RESIDUO_EMPRESA.NIF_EMPRESA;

--9. Mostrar el nombre de las diferentes empresas que han enviado residuos que contenga la
--palabra metales en su descripción.
SELECT DISTINCT EMPRESAPRODUCTORA.NOMBRE_EMPRESA
FROM RESIDUO, RESIDUO_EMPRESA, EMPRESAPRODUCTORA
WHERE  RESIDUO.COD_RESIDUO = RESIDUO_EMPRESA.COD_RESIDUO
AND RESIDUO_EMPRESA.NIF_EMPRESA = EMPRESAPRODUCTORA.NIF_EMPRESA 
AND UPPER(RESIDUO.OD_RESIDUO) LIKE '%METALES%';

--10. Mostrar el número de envíos que se han realizado entre cada ciudad, indicando también la
--ciudad origen y la ciudad destino.
SELECT COUNT(DESTINO.COD_DESTINO),DESTINO.CIUDAD_DESTINO, EMPRESATRANSPORTISTA.CIUDAD_EMPTRANSPORTE
FROM TRASLADO, EMPRESATRANSPORTISTA, DESTINO
WHERE TRASLADO.NIF_EMPTRANSPORTE = EMPRESATRANSPORTISTA.NIF_EMPTRANSPORTE
AND DESTINO.COD_DESTINO = TRASLADO.COD_DESTINO
GROUP BY DESTINO.CIUDAD_DESTINO, EMPRESATRANSPORTISTA.CIUDAD_EMPTRANSPORTE;


--11. Mostrar el nombre de la empresa transportista que ha transportado para una empresa que
--esté en Málaga o en Huelva un residuo que contenga Bario o Lantano. 
--Mostrar también la fecha del transporte.
SELECT EMPRESATRANSPORTISTA.NOMBRE_EMPTRANSPORTE, TRASLADO.FECHA_ENVIO
FROM EMPRESATRANSPORTISTA, TRASLADO, EMPRESAPRODUCTORA, RESIDUO
WHERE EMPRESAPRODUCTORA.NIF_EMPRESA = TRASLADO.NIF_EMPRESA
AND TRASLADO.NIF_EMPRESA = EMPRESAPRODUCTORA.NIF_EMPRESA
AND RESIDUO.COD_RESIDUO = TRASLADO.COD_RESIDUO
AND (UPPER(EMPRESAPRODUCTORA.CIUDAD_EMPRESA) LIKE 'HUELVA'
OR UPPER(EMPRESAPRODUCTORA.CIUDAD_EMPRESA) LIKE 'MÁLAGA')
AND (UPPER(RESIDUO.OD_RESIDUO) LIKE '%BARIO%' 
OR UPPER(RESIDUO.OD_RESIDUO) LIKE '%LANTANO%');


--12. Mostrar el coste por kilómetro del total de traslados encargados por la empresa productora
--Carbonsur.
SELECT ROUND(SUM(TRASLADO.COSTE) / SUM(TRASLADO.KMS),2) coste_total_por_km
FROM TRASLADO, EMPRESAPRODUCTORA
WHERE EMPRESAPRODUCTORA.NIF_EMPRESA = TRASLADO.NIF_EMPRESA
AND UPPER(EMPRESAPRODUCTORA.NOMBRE_EMPRESA) LIKE 'CARBONSUR';

--13. Mostrar el número de constituyentes de cada residuo.
SELECT COUNT(RESIDUO_CONSTITUYENTE.COD_CONSTITUYENTE) num_cont
FROM RESIDUO_CONSTITUYENTE
GROUP BY RESIDUO_CONSTITUYENTE.COD_RESIDUO;

--14. Mostrar la descripción de los residuos y la fecha que se generó el residuo, para aquellos
--residuos que se han generado en los últimos 30 días por una empresa cuyo nombre tenga una
--c. La consulta debe ser válida para cualquier fecha y el listado debe aparecer ordenado por la
--descripción del residuo y la fecha.
SELECT RESIDUO.OD_RESIDUO, RESIDUO_EMPRESA.FECHA
FROM RESIDUO, RESIDUO_EMPRESA, EMPRESAPRODUCTORA
WHERE RESIDUO.COD_RESIDUO = RESIDUO_EMPRESA.COD_RESIDUO
AND EMPRESAPRODUCTORA.NIF_EMPRESA = RESIDUO_EMPRESA.NIF_EMPRESA
AND UPPER(EMPRESAPRODUCTORA.NOMBRE_EMPRESA) LIKE '%C%'
AND RESIDUO_EMPRESA.FECHA > add_months(sysdate, -1)
ORDER BY EMPRESAPRODUCTORA.OD_EMPRESA DESC, RESIDUO_EMPRESA.FECHA DESC;


